pipeline:
  name: default
  description: Default build pipeline

stages:
  - build
  - test
  - doc

compile:
  - stage: build
  - image: gradle:jdk21-corretto
  - script: 'gradle build'

checkstyle:
  - stage: test
  - image: gradle:jdk21-corretto
  - script: 'gradle checkstyleMain'

unittest:
  - stage: test
  - image: gradle:jdk21-corretto
  - needs: [checkstyle]
  - script: 'gradle test jacocoTestReport'

docs:
  - stage: doc
  - image: gradle:jdk21-corretto
  - script: 'gradle javadoc'