pipeline:
  name: default
  description: Default build pipeline

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  image: gradle:jdk17
  script: ./gradlew build

checkstyle:
  stage: test
  image: gradle:jdk17
  script: ./gradlew checkstyleMain

unittest:
  stage: test
  image: gradle:jdk17
  needs:
    - checkstyle
  script:
    - ./gradlew test
    - ./gradlew jacocoTestReport

package:
  stage: deploy
  image: gradle:jdk17
  script: ./gradlew publish